version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "go"
      include: "scope"
    # Add secrets access for Go updates
    secrets:
      - AWS_REGION
      - AWS_ROLE_TO_ASSUME

  # API Dockerfile
  - package-ecosystem: "docker"
    directory: "/cmd/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
      - "api"
    commit-message:
      prefix: "docker"
      include: "scope"
    # Add secrets access for API Docker updates
    secrets:
      - AWS_REGION
      - AWS_ROLE_TO_ASSUME

  # Worker Dockerfile
  - package-ecosystem: "docker"
    directory: "/cmd/worker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
      - "worker"
    commit-message:
      prefix: "docker"
      include: "scope"
    # Add secrets access for Worker Docker updates
    secrets:
      - AWS_REGION
      - AWS_ROLE_TO_ASSUME